<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<style>
    .product-image {
        width: 70px;
        height: 70px;
    }
</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<h1>Your Cart</h1>
<div class="container">
    <table class="table ">
        <thead>
            <tr>
                <th class="d-none d-sm-table-cell"></th>
                <th>Product</th>
                <th class="d-none d-sm-table-cell">Price/pcs</th>
                <th>Quantity</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            <?php if (!empty($this->cart)) : ?>
                <?php foreach ($this->cart as $key => $value) : ?>
                    <tr>
                        <td class="d-none d-sm-table-cell"><img class="product-image" src="<?php echo $this->escapeHtml($value["productImage"]); ?>" alt="<?php echo $value["productName"]; ?>" class="img-fluid"></td>
                        <td><?php echo $this->escapeHtml($value["productName"]); ?></td>
                        <td class="d-none d-sm-table-cell"><?php echo $this->escapeHtml($value["productPrice"]); ?> kr</td>
                        <td><?php echo $this->escapeHtml($value["productQty"]); ?></td>
                        <td><?php echo $this->escapeHtml($value["productTotalRowPrice"]); ?> kr</td>
                        <td><button onclick="removeCartItem(<?php echo $this->escapeHtml($value['productId']); ?>)" class="btn btn-danger"><i class="fas fa-trash"></i></button></td>
                    </tr>
                <?php endforeach; ?>
            <?php else : ?>
                <p>Your cart is empty.</p>
            <?php endif; ?>

            <!-- Repeat the above row for each product -->
        </tbody>
    </table>
</div>