<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="p-0 mb-4 bg-light rounded-3">
    <h1 class="display-4">About us</h1>

    <p>
        Welcome to our webshop! We are dedicated to providing high-quality cosmetic products to our customers. Our mission is to enhance your natural beauty and boost your confidence. With a wide range of products carefully selected from trusted brands, we strive to meet all your beauty needs. Whether you're looking for skincare, makeup, or haircare products, we've got you covered. Shop with us and experience the joy of self-care and self-expression through cosmetics.
    </p>
</div>