<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Du shoppa')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>
    <?= $this->headLink([
        'rel' => 'stylesheet',
        'href' => 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css'
    ]) ?>
    <!-- Scripts -->

    <?= $this->headScript()->appendFile($this->basePath() . '/js/customjs.js');  ?>

</head>


<body>
    <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" alt="Du shoppa">

            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto">

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="<?= $this->url('home') ?>">Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="<?= $this->url('about') ?>">About
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="<?= $this->url('contact') ?>">Contact us
                        </a>
                    </li>

                    <li class="nav-item dropdown" onclick='viewMiniCart()'>
                        <a class="nav-link dropdown-toggle" href="#" id="cartDropdown" role="button" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
                            <i class="fas fa-shopping-basket"></i>
                            <?php
                            echo "<span id='cart-counter'>$cartCount</span>";
                            ?>
                        </a>
                        <ul id="dynamicDropDown" class="dropdown-menu dropdown-menu-end minicart-dropdown" aria-labelledby="cartDropdown">
                            <li><a class="dropdown-item btn bg-warning text-center" href="<?= $this->url('cart') ?>">View Cart</a></li> <?php if (empty($miniCartProducts)) : ?>

                                <table class="minicart-table">
                                    <thead>
                                        <tr class="border-bottom">
                                            <th></th>
                                            <th>Product</th>
                                            <th>Quantity</th>
                                            <th>Price</th>

                                        </tr>
                                    </thead>
                                    <tbody>


                                    </tbody>
                                </table>
                            <?php else : ?>
                                <table class="minicart-table">
                                    <thead>
                                        <tr class="border-bottom">
                                            <th></th>
                                            <th>Product</th>
                                            <th>Quantity</th>
                                            <th>Price</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($miniCartProducts as $productArrary => $product) : ?>
                                            <tr class="border-bottom">
                                                <td><img src="<?= $product["miniImage"] ?>" alt="<?= $product["miniName"] ?>" style="width: 50px; height: 50px;"></td>
                                                <td class="text-capitalize"><?= $product["miniName"] ?></td>
                                                <td>+<?= $product["miniQty"] ?>-</td>
                                                <td><?= $product["miniPrice"] ?> kr</td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            <?php endif; ?>

                            <li><a class="dropdown-item btn bg-warning text-center" href="<?= $this->url('cart') ?>">View Cart</a></li>
                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <?= $this->content ?>
        <hr>
        <footer>
            <p>
                &copy; <?= date('Y') ?>
                <a href="/">Du shoppa</a>
            </p>
        </footer>
    </div>
    <?= $this->inlineScript()
        ->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js')
        ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js')
    // ->prependFile($this->basePath('js/bootstrap.min.js')) 
    ?>
</body>

</html>