<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Du shoppa')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>
    <?= $this->headLink([
        'rel' => 'stylesheet',
        'href' => 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css'
    ]) ?>
    <!-- Scripts -->

    <?= $this->headScript()->appendFile($this->basePath() . '/js/customjs.js');  ?>

</head>


<body>
    <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img class="col-4 col-md-2" src="<?= $this->basePath('img/dushoppa.png') ?>" alt="Du shoppa">

            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto">

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="<?= $this->url('home') ?>">Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="<?= $this->url('about') ?>">About
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="<?= $this->url('contact') ?>">Contact us
                        </a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="cartDropdown" role="button" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
                            <i class="fas fa-shopping-basket"></i>
                            <?php
                            echo "<span id='cart-counter'>$cartCount</span>";
                            ?>
                        </a>
                        <ul id="dynamicDropDown" class="dropdown-menu dropdown-menu-end minicart-dropdown" aria-labelledby="cartDropdown">
                            <li><a class="dropdown-item btn bg-warning text-center" href="<?= $this->url('cart') ?>">View Cart</a></li>

                            <table class="minicart-table" id="cart-table">
                                <thead>
                                    <tr class="border-bottom">
                                        <th></th>
                                        <th>Product</th>
                                        <th>Quantity</th>
                                        <th>Price</th>

                                    </tr>
                                </thead>
                                <tbody>

                                    <?php if (empty($miniCart)) : ?>
                                        <div id="deleteOnRefresh" class="d-flex justify-content-center align-items-center" style="height: 200px;">
                                            <div class="alert alert-warning" role="alert">
                                                Your cart is empty
                                            </div>
                                        </div>


                                </tbody>
                            </table>
                        <?php else : ?>

                            <?php foreach ($miniCart as $id => $product) : ?>
                                <tr class="border-bottom">
                                    <td><img src="<?= $product["productImage"] ?>" alt="<?= $product["productName"] ?>" style="width: 50px; height: 50px;"></td>
                                    <td class="text-capitalize"><?= $product["productName"] ?></td>
                                    <td><span class="mini-add" onclick="addToCart(<?= $this->escapeHtml($product['productId']); ?>)">+</span><?= $product["productQty"] ?><span class="mini-add" onclick="removeOne(<?= $this->escapeHtml($product['productId']); ?>)">-</span></td>
                                    <td><?= $product["productTotalRowPrice"] ?> kr</td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                            </table>

                        <?php endif; ?>

                        <li><a class="dropdown-item btn bg-warning text-center" href="<?= $this->url('cart') ?>">View Cart</a></li>
                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <?= $this->content ?>
        <hr>
        <footer>
            <p>
                &copy; <?= date('Y') ?>
                <a href="/">Du shoppa</a>
            </p>
        </footer>
    </div>
    <?= $this->inlineScript()
        ->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js')
    // ->prependFile($this->basePath('js/bootstrap.min.js')) 
    ?>
</body>

</html>