<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>



<div class="p-0 mb-4 bg-light rounded-3">
    <h1 class="display-4">Welcome to Dushoppa</h1>

    <p>
        Checkout range of our products
    </p>



</div>
<style>
    .card-img-top {
        height: 200px;
        object-fit: cover;
    }
</style>
<div id="products" class="row">
    <?php foreach ($products as $product) : ?>
        <!-- Change "col-md-4" to "col-6 col-md-4" so that on medium devices and up it uses the existing styling, and on small devices it shows 2 per row -->
        <div class="col-6 col-md-4">
            <div class="card mb-4 shadow-sm">
                <img class="bd-placeholder-img card-img-top" src="<?php echo $this->escapeHtml($product->image); ?>" alt="<?php echo $this->escapeHtml($product->name); ?>">
                <div class="card-body">
                    <h2 class="card-title text-capitalize small"><?php echo $this->escapeHtml(mb_strimwidth($product->name, 0, 10, "...")); ?></h2>
                    <p class="card-text"><?php echo $this->escapeHtml($product->description); ?></p>


                    <div class="text-muted"><?php echo $this->escapeHtml($product->price); ?> kr</div>

                    <button type="button" class="btn btn-sm btn-outline-secondary w-100" onclick="addToCart(<?php echo $product->id; ?>)">Add to Cart</button>



                </div>
            </div>
        </div>
    <?php endforeach ?>
</div>