<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

<div class="p-0 mb-4 rounded-3">
    <h1 class="display-4">Welcome to Dushoppa</h1>

    <p>
        Checkout range of our products
    </p>



</div>
<style>
    .card-img-top {
        height: 200px;
        object-fit: cover;
    }
</style>
<div id="products" class="row">
    <?php foreach ($products as $product) : ?>
        <div class="col-6 col-md-3">
            <div class="card mb-4 shadow-sm">
                <img class="bd-placeholder-img card-img-top" src="<?php echo $this->escapeHtml($product->image); ?>" alt="<?php echo $this->escapeHtml($product->name); ?>">
                <div class="card-body">
                    <h2 class="card-title text-capitalize small"><?php echo $this->escapeHtml(mb_strimwidth($product->name, 0, 10, "...")); ?></h2>
                    <p class="card-text"><?php echo $this->escapeHtml($product->description); ?></p>

                    <!-- Star rating -->

                    <div class="mb-3">
                        <?php $star = mt_rand(1, 5); ?>
                        <?php for ($i = 0; $i < $star; $i++) : ?>
                            <i class="bi bi-star-fill"></i>
                        <?php endfor; ?>
                    </div>

                    <div class="text-muted"><?php echo $this->escapeHtml($product->price); ?> kr</div>

                    <button type="button" class="btn btn-sm btn-outline-secondary w-100" onclick="addToCart(<?php echo $product->id; ?>)">Add to Cart</button>
                </div>
            </div>
        </div>
    <?php endforeach ?>
</div>