name: PHP CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1 #  AWS region

      - name: Get runner's IP address
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Whitelist runner IP address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id sg-0739e6e8005beba1b \
            --protocol tcp \
            --port 22 \
            --source-group sg-0739e6e8005beba1b
            
      - name: Set up SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > dushoppaKey.pem
          chmod 400 dushoppaKey.pem
          
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "heelo"
            
      - name: Revoke runner IP address
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id sg-0739e6e8005beba1b \
            --protocol tcp \
            --port 22 \
            --source-group sg-0739e6e8005beba1b
